version: 0.2

phases:
  install:
    commands:
      - cd smart-docs-ai/smart-docs-ai
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: smart-docs-ai/smart-docs-ai/dist
  files:
    - '**/*'